<?php $this->widget('EExcelView', array(
                                'grid_mode'=>'export',
                                'dataProvider'=>$model->search(),
                                'filter'=>$model,
                                'title'=>"Agricultors",
                                'creator'=>'GoldStarNet',   
                                'autoWidth'=>true,   
                                'columns'=>array(
                            			array(
				'name'=>'id',
				'type'=>'html',
				'htmlOptions'=>array('style'=>'word-wrap: break-word;'),
				'headerHtmlOptions'=>array('style'=>'text-align:center;'),
				'filterHtmlOptions'=>array('style'=>'width:70px'),
				'value'=>'"<div style=\"text-align:center;width:70px;\">" . $data["id"] . "</div>"',
				),
			array(
				'name'=>'rut',
				),
			array(
				'name'=>'razonSocial',
				),
			array(
				'name'=>'direccion',
				),
			array(
				'name'=>'email',
				),
			array(
				'name'=>'telefono',
				),
			array(
				'name'=>'propiedad1',
				),
			array(
				'name'=>'propiedad2',
				),
			array(
				'name'=>'propiedad3',
				),
			array(
				'name'=>'propiedad4',
				),
			array(
				'name'=>'propiedad5',
				),
			array(
				'name'=>'propiedad6',
				),
			array(
				'name'=>'propiedad7',
				),
			array(
				'name'=>'propiedad8',
				),
			array(
				'name'=>'propiedad9',
				),
			array(
				'name'=>'propiedad10',
				),
			array(
				'name'=>'propiedad11',
				),
			array(
				'name'=>'propiedad12',
				),
			array(
				'name'=>'propiedad13',
				),
			array(
				'name'=>'propiedad14',
				),
			array(
				'name'=>'propiedad15',
				),
			array(
				'name'=>'propiedad16',
				),
			array(
				'name'=>'status',
				),
			array(
				'name'=>'used_by',
				),
			array(
				'name'=>'check_in',
				),
			array(
				'name'=>'created_by',
				),
			array(
				'name'=>'created',
				),
			array(
				'name'=>'modified_by',
				),
			array(
				'name'=>'modified',
				),
                            ),
                            )); ?>                        

