<?php

/**
 * This is the model base class for the table "contratoagricultor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ContratoAgricultor".
 *
 * Columns in table "contratoagricultor" available as properties of the model,
 * followed by relations of table "contratoagricultor" available as properties of the model.
 *
 * @property integer $id
 * @property integer $temporada_id
 * @property integer $agricultor_id
 * @property integer $especie_id
 * @property integer $contratoclientedetalle_id
 * @property string $status
 * @property integer $used_by
 * @property string $check_in
 * @property integer $created_by
 * @property string $created
 * @property integer $modified_by
 * @property string $modified
 *
 * @property Agricultor $agricultor
 * @property Contratoclientedetalle $contratoclientedetalle
 * @property Especie $especie
 * @property Temporada $temporada
 * @property Fbdato[] $fbdatos
 */
abstract class BaseContratoAgricultor extends AweActiveRecord {


    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'contratoagricultor';
    }

    public static function representingColumn() {
        return 'status';
    }

    public function rules() {
        return array(
            array(	'temporada_id, agricultor_id, especie_id',
					'required',
					'message' => Yii::t('app', 'Field is required')
			),
            array(	'temporada_id, agricultor_id, especie_id, contratoclientedetalle_id, used_by, created_by, modified_by',
					'numerical',
					'integerOnly'=>true
			),
            array(	'status',
					'length',
					'max'=>1,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'check_in, created, modified',
					'safe'
			),
            array('contratoclientedetalle_id, status, used_by, check_in, created_by, created, modified_by, modified',
					'default',
					'setOnEmpty' => true,
					'value' => null
			),
            array('id, temporada_id, agricultor_id, especie_id, contratoclientedetalle_id, status, used_by, check_in, created_by, created, modified_by, modified', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'agricultor' => array(self::BELONGS_TO, 'Agricultor', 'agricultor_id'),
            'contratoclientedetalle' => array(self::BELONGS_TO, 'Contratoclientedetalle', 'contratoclientedetalle_id'),
            'especie' => array(self::BELONGS_TO, 'Especie', 'especie_id'),
            'temporada' => array(self::BELONGS_TO, 'Temporada', 'temporada_id'),
            'fbdatos' => array(self::HAS_MANY, 'Fbdato', 'contrtoAgricultor_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'temporada_id' => Yii::t('app', 'Temporada'),
                'agricultor_id' => Yii::t('app', 'Agricultor'),
                'especie_id' => Yii::t('app', 'Especie'),
                'contratoclientedetalle_id' => Yii::t('app', 'Contratoclientedetalle'),
                'status' => Yii::t('app', 'Status'),
                'used_by' => Yii::t('app', 'Used By'),
                'check_in' => Yii::t('app', 'Check In'),
                'created_by' => Yii::t('app', 'Created By'),
                'created' => Yii::t('app', 'Created'),
                'modified_by' => Yii::t('app', 'Modified By'),
                'modified' => Yii::t('app', 'Modified'),
                'agricultor' => null,
                'contratoclientedetalle' => null,
                'especie' => null,
                'temporada' => null,
                'fbdatos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('temporada_id', $this->temporada_id);
        $criteria->compare('agricultor_id', $this->agricultor_id);
        $criteria->compare('especie_id', $this->especie_id);
        $criteria->compare('contratoclientedetalle_id', $this->contratoclientedetalle_id);
        $criteria->compare('status', $this->status, true);
        $criteria->compare('used_by', $this->used_by);
        $criteria->compare('check_in', $this->check_in, true);
        $criteria->compare('created_by', $this->created_by);
        $criteria->compare('created', $this->created, true);
        $criteria->compare('modified_by', $this->modified_by);
        $criteria->compare('modified', $this->modified, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}