<?php

/**
 * This is the model base class for the table "agricultor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Agricultor".
 *
 * Columns in table "agricultor" available as properties of the model,
 * followed by relations of table "agricultor" available as properties of the model.
 *
 * @property integer $id
 * @property string $rut
 * @property string $razonSocial
 * @property string $direccion
 * @property string $email
 * @property string $telefono
 * @property string $status
 * @property integer $used_by
 * @property string $check_in
 * @property integer $created_by
 * @property string $created
 * @property integer $modified_by
 * @property string $modified
 *
 * @property Contratoagricultor[] $contratoagricultors
 */
abstract class BaseAgricultor extends AweActiveRecord {


    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'agricultor';
    }

    public static function representingColumn() {
        return 'rut';
    }

    public function rules() {
        return array(
            array(	'rut, razonSocial, direccion',
					'required',
					'message' => Yii::t('app', 'Field is required')
			),
            array(	'used_by, created_by, modified_by',
					'numerical',
					'integerOnly'=>true
			),
            array(	'rut',
					'length',
					'max'=>10,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'razonSocial, direccion',
					'length',
					'max'=>100,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'email, telefono',
					'length',
					'max'=>50,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'status',
					'length',
					'max'=>1,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'check_in, created, modified',
					'safe'
			),
            array('email, telefono, status, used_by, check_in, created_by, created, modified_by, modified',
					'default',
					'setOnEmpty' => true,
					'value' => null
			),
            array('id, rut, razonSocial, direccion, email, telefono, status, used_by, check_in, created_by, created, modified_by, modified', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'contratoagricultors' => array(self::HAS_MANY, 'Contratoagricultor', 'agricultor_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'rut' => Yii::t('app', 'Rut'),
                'razonSocial' => Yii::t('app', 'Razon Social'),
                'direccion' => Yii::t('app', 'Direccion'),
                'email' => Yii::t('app', 'Email'),
                'telefono' => Yii::t('app', 'Telefono'),
                'status' => Yii::t('app', 'Status'),
                'used_by' => Yii::t('app', 'Used By'),
                'check_in' => Yii::t('app', 'Check In'),
                'created_by' => Yii::t('app', 'Created By'),
                'created' => Yii::t('app', 'Created'),
                'modified_by' => Yii::t('app', 'Modified By'),
                'modified' => Yii::t('app', 'Modified'),
                'contratoagricultors' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('rut', $this->rut, true);
        $criteria->compare('razonSocial', $this->razonSocial, true);
        $criteria->compare('direccion', $this->direccion, true);
        $criteria->compare('email', $this->email, true);
        $criteria->compare('telefono', $this->telefono, true);
        $criteria->compare('status', $this->status, true);
        $criteria->compare('used_by', $this->used_by);
        $criteria->compare('check_in', $this->check_in, true);
        $criteria->compare('created_by', $this->created_by);
        $criteria->compare('created', $this->created, true);
        $criteria->compare('modified_by', $this->modified_by);
        $criteria->compare('modified', $this->modified, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}