<?php

/**
 * This is the model base class for the table "cliente".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cliente".
 *
 * Columns in table "cliente" available as properties of the model,
 * followed by relations of table "cliente" available as properties of the model.
 *
 * @property integer $id
 * @property string $rut
 * @property string $nombre
 * @property string $nombreCorto
 * @property string $abrev
 * @property string $status
 * @property integer $used_by
 * @property string $check_in
 * @property integer $created_by
 * @property string $created
 * @property integer $modified_by
 * @property string $modified
 *
 * @property Catalogo[] $catalogos
 * @property Clientecontacto[] $clientecontactos
 * @property Clientedireccion[] $clientedireccions
 * @property Contratocliente[] $contratoclientes
 */
abstract class BaseCliente extends AweActiveRecord {


    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'cliente';
    }

    public static function representingColumn() {
        return 'rut';
    }

    public function rules() {
        return array(
            array(	'rut, nombre, abrev',
					'required',
					'message' => Yii::t('app', 'Field is required')
			),
            array(	'used_by, created_by, modified_by',
					'numerical',
					'integerOnly'=>true
			),
            array(	'rut',
					'length',
					'max'=>10,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'nombre',
					'length',
					'max'=>100,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'nombreCorto, abrev',
					'length',
					'max'=>20,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'status',
					'length',
					'max'=>1,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'check_in, created, modified',
					'safe'
			),
            array('nombreCorto, status, used_by, check_in, created_by, created, modified_by, modified',
					'default',
					'setOnEmpty' => true,
					'value' => null
			),
            array('id, rut, nombre, nombreCorto, abrev, status, used_by, check_in, created_by, created, modified_by, modified', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'catalogos' => array(self::HAS_MANY, 'Catalogo', 'cliente_id'),
            'clientecontactos' => array(self::HAS_MANY, 'Clientecontacto', 'cliente_id'),
            'clientedireccions' => array(self::HAS_MANY, 'Clientedireccion', 'cliente_id'),
            'contratoclientes' => array(self::HAS_MANY, 'Contratocliente', 'cliente_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'rut' => Yii::t('app', 'Rut'),
                'nombre' => Yii::t('app', 'Nombre'),
                'nombreCorto' => Yii::t('app', 'Nombre Corto'),
                'abrev' => Yii::t('app', 'Abrev'),
                'status' => Yii::t('app', 'Status'),
                'used_by' => Yii::t('app', 'Used By'),
                'check_in' => Yii::t('app', 'Check In'),
                'created_by' => Yii::t('app', 'Created By'),
                'created' => Yii::t('app', 'Created'),
                'modified_by' => Yii::t('app', 'Modified By'),
                'modified' => Yii::t('app', 'Modified'),
                'catalogos' => null,
                'clientecontactos' => null,
                'clientedireccions' => null,
                'contratoclientes' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('rut', $this->rut, true);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('nombreCorto', $this->nombreCorto, true);
        $criteria->compare('abrev', $this->abrev, true);
        $criteria->compare('status', $this->status, true);
        $criteria->compare('used_by', $this->used_by);
        $criteria->compare('check_in', $this->check_in, true);
        $criteria->compare('created_by', $this->created_by);
        $criteria->compare('created', $this->created, true);
        $criteria->compare('modified_by', $this->modified_by);
        $criteria->compare('modified', $this->modified, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}