<?php

/**
 * This is the model base class for the table "fieldbook".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Fieldbook".
 *
 * Columns in table "fieldbook" available as properties of the model,
 * followed by relations of table "fieldbook" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $familia_id
 * @property integer $temporada_id
 * @property string $status
 * @property integer $used_by
 * @property string $check_in
 * @property integer $created_by
 * @property string $created
 * @property integer $modified_by
 * @property string $modified
 *
 * @property Fbcolasignada[] $fbcolasignadas
 * @property Familia $familia
 * @property Temporada $temporada
 */
abstract class BaseFieldbook extends AweActiveRecord {


    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'fieldbook';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array(	'nombre, familia_id, temporada_id',
					'required',
					'message' => Yii::t('app', 'Field is required')
			),
            array(	'familia_id, temporada_id, used_by, created_by, modified_by',
					'numerical',
					'integerOnly'=>true
			),
            array(	'nombre',
					'length',
					'max'=>50,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'status',
					'length',
					'max'=>1,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'check_in, created, modified',
					'safe'
			),
            array('status, used_by, check_in, created_by, created, modified_by, modified',
					'default',
					'setOnEmpty' => true,
					'value' => null
			),
            array('id, nombre, familia_id, temporada_id, status, used_by, check_in, created_by, created, modified_by, modified', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'fbcolasignadas' => array(self::HAS_MANY, 'Fbcolasignada', 'fieldbook_id'),
            'familia' => array(self::BELONGS_TO, 'Familia', 'familia_id'),
            'temporada' => array(self::BELONGS_TO, 'Temporada', 'temporada_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'familia_id' => Yii::t('app', 'Familia'),
                'temporada_id' => Yii::t('app', 'Temporada'),
                'status' => Yii::t('app', 'Status'),
                'used_by' => Yii::t('app', 'Used By'),
                'check_in' => Yii::t('app', 'Check In'),
                'created_by' => Yii::t('app', 'Created By'),
                'created' => Yii::t('app', 'Created'),
                'modified_by' => Yii::t('app', 'Modified By'),
                'modified' => Yii::t('app', 'Modified'),
                'fbcolasignadas' => null,
                'familia' => null,
                'temporada' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('familia_id', $this->familia_id);
        $criteria->compare('temporada_id', $this->temporada_id);
        $criteria->compare('status', $this->status, true);
        $criteria->compare('used_by', $this->used_by);
        $criteria->compare('check_in', $this->check_in, true);
        $criteria->compare('created_by', $this->created_by);
        $criteria->compare('created', $this->created, true);
        $criteria->compare('modified_by', $this->modified_by);
        $criteria->compare('modified', $this->modified, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}