<?php

/**
 * This is the model base class for the table "variedad".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Variedad".
 *
 * Columns in table "variedad" available as properties of the model,
 * followed by relations of table "variedad" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $especie_id
 * @property integer $cliente_id
 * @property string $codigoGoldStar
 * @property string $status
 * @property integer $used_by
 * @property string $check_in
 * @property integer $created_by
 * @property string $created
 * @property integer $modified_by
 * @property string $modified
 *
 * @property Contratoclientedetalle[] $contratoclientedetalles
 * @property Cliente $cliente
 * @property Especie $especie
 */
abstract class BaseVariedad extends AweActiveRecord {


    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'variedad';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array(	'nombre, especie_id, codigoGoldStar',
					'required',
					'message' => Yii::t('app', 'Field is required')
			),
            array(	'especie_id, cliente_id, used_by, created_by, modified_by',
					'numerical',
					'integerOnly'=>true
			),
            array(	'nombre, codigoGoldStar',
					'length',
					'max'=>50,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'status',
					'length',
					'max'=>1,
					'tooLong' => Yii::t('app', 'Field is required')
			),
            array(	'check_in, created, modified',
					'safe'
			),
            array('cliente_id, status, used_by, check_in, created_by, created, modified_by, modified',
					'default',
					'setOnEmpty' => true,
					'value' => null
			),
            array('id, nombre, especie_id, cliente_id, codigoGoldStar, status, used_by, check_in, created_by, created, modified_by, modified', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'contratoclientedetalles' => array(self::HAS_MANY, 'Contratoclientedetalle', 'variedad_id'),
            'cliente' => array(self::BELONGS_TO, 'Cliente', 'cliente_id'),
            'especie' => array(self::BELONGS_TO, 'Especie', 'especie_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'especie_id' => Yii::t('app', 'Especie'),
                'cliente_id' => Yii::t('app', 'Cliente'),
                'codigoGoldStar' => Yii::t('app', 'Codigo Gold Star'),
                'status' => Yii::t('app', 'Status'),
                'used_by' => Yii::t('app', 'Used By'),
                'check_in' => Yii::t('app', 'Check In'),
                'created_by' => Yii::t('app', 'Created By'),
                'created' => Yii::t('app', 'Created'),
                'modified_by' => Yii::t('app', 'Modified By'),
                'modified' => Yii::t('app', 'Modified'),
                'contratoclientedetalles' => null,
                'cliente' => null,
                'especie' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('especie_id', $this->especie_id);
        $criteria->compare('cliente_id', $this->cliente_id);
        $criteria->compare('codigoGoldStar', $this->codigoGoldStar, true);
        $criteria->compare('status', $this->status, true);
        $criteria->compare('used_by', $this->used_by);
        $criteria->compare('check_in', $this->check_in, true);
        $criteria->compare('created_by', $this->created_by);
        $criteria->compare('created', $this->created, true);
        $criteria->compare('modified_by', $this->modified_by);
        $criteria->compare('modified', $this->modified, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}